/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as ClassifyMultiRouteImport } from './routes/classify-multi'
import { Route as ClassifyRouteImport } from './routes/classify'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'

const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyMultiRoute = ClassifyMultiRouteImport.update({
  id: '/classify-multi',
  path: '/classify-multi',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyRoute = ClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/classify': typeof ClassifyRoute
  '/classify-multi': typeof ClassifyMultiRoute
  '/guidance': typeof GuidanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/classify': typeof ClassifyRoute
  '/classify-multi': typeof ClassifyMultiRoute
  '/guidance': typeof GuidanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/classify': typeof ClassifyRoute
  '/classify-multi': typeof ClassifyMultiRoute
  '/guidance': typeof GuidanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog' | '/classify' | '/classify-multi' | '/guidance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/classify' | '/classify-multi' | '/guidance'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/classify'
    | '/classify-multi'
    | '/guidance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ClassifyRoute: typeof ClassifyRoute
  ClassifyMultiRoute: typeof ClassifyMultiRoute
  GuidanceRoute: typeof GuidanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify-multi': {
      id: '/classify-multi'
      path: '/classify-multi'
      fullPath: '/classify-multi'
      preLoaderRoute: typeof ClassifyMultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify': {
      id: '/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof ClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ClassifyRoute: ClassifyRoute,
  ClassifyMultiRoute: ClassifyMultiRoute,
  GuidanceRoute: GuidanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
